export const data = [
  {
    name: '"MONEYMAKER" TEE IN TAN dasdasdasd asdas dasd asdas dasdas dasd asdasdasdasdqwdawdwqaeqwdasdqwed',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img1.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img2.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img3.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img4.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img5.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img6.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img1.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img2.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img3.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img4.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img5.png"),
  },
  {
    name: '"MONEYMAKER" TEE IN TAN',
    price: 99,
    iconHeart: "bx-heart.svg",
    iconCart: "bx-cart.svg",
    img: require("../../src/assets/images/img6.png"),
  },
];
